manual:
  path: "/path/to/thespecs" # optional path to specs root, defaults to "specs"
  publish_path: "path/to/report" # optional Testspace result's path to publish status to, defaults to ""

issues:
  provider: # optional, defaults to "github:" (current org/repo)
  label: # optional, defaults to "testspace"

release: "*_rel" # optional one or more branch-wildcard entries

commit_status: true # optional, defaults to true
